### PR TITLE
Added ASCII graphics for Redox

### PR DESCRIPTION
**Pull request by paezao**

### CODE REVIEW

**Comment by jackpot51** [comment]
It looks good. Is it possible to have all the #[cfg(target_os = "redox")] inside of one block like this?

```
#[cfg(target_os = "redox")]
{
    SOMETHING = "|";
    SOMETHING_ELSE = "=";
}
```

**Comment by ticki** [comment]
> It looks good. Is it possible to have all the #[cfg(target_os = "redox")] inside of one block like this?

Unfortunately not.

**Comment by paezao** [comment]
It's possible. I did it haha. I used a mod

**Comment by jackpot51** [comment]
Very clever

**Pull request merged**
