### PR TITLE
Interface fixing with ASCII chars

### PR DESCRIPTION
**Pull request by HenryTheCat**
Now it _really_ should be usable.

### CODE REVIEW

**Comment by ticki** [comment]
Travis fails.

**Comment by HenryTheCat** [comment]
According to Travis, build is failing because I used `i32` as an argument for `Duration::new( , )`. According to docs (http://ticki.github.io/redocs/std/time/struct.Duration.html) the correct type used to be `u32` but changed to `i32` at some point. I guess it's just a Rust version problem...

**Comment by ticki** [comment]
> I guess it's just a Rust version problem...

Nope, it's a Redox libstd compatibility program.

**Comment by HenryTheCat** [comment]
Should I change it back to `u32`? Because right now, when compiling redox with the updated rusthello, Cargo demands a `i32` instead.

**Comment by jackpot51** [comment]
Have updated libstd

**Comment by jackpot51** [comment]
Merged and fixed in another commit, it should be building now (on linux and redox)

**Pull request merged**
