### PR TITLE
[WARNING] Big RUSThello update

### PR DESCRIPTION
**Pull request by HenryTheCat**
Big update with many small fixes.

Beware, before merging:

* I didn’t manage to test this in Redox, so it may break everything! Can someone test it on Redox?
* Now dependencies include `rand`, `rayon` and `reversi` (library powering rusthello hosted on GitHub).
* I bumped `termion` version to `1.4.*`. Everything seems to work fine but it’s difficult to tell for sure. If this seems too risky, consider reverting the change.

### CODE REVIEW

**Comment by HenryTheCat** [comment]
Does Redox's terminal support Unicode chars? Because otherwise there are a few in rusthello's interface which should be substituted with asii ones…

**Comment by jackpot51** [comment]
Yes, it does @EGhiorzi

**Comment by jackpot51** [comment]
I am testing, will merge if it works!

**Comment by jackpot51** [comment]
So, in the reversi crate you `extern crate test` when not needed.

You should wrap it in `#[cfg(test)]`

**Comment by HenryTheCat** [comment]
I refactored the tests and benches on both the library and the game itself, which is mostrly not visible since I don't include these here. Though, rusthello now has to be both a bin and a library. That is why I had to add a few lines to the `Cargo.toml`, hope it's ok.

The good thing is that now `extern crate test` is not used, and it's possible to build with the release version of `rustc`.

Also, I noticed that the interface is somewhat slow. This is probably due to the many `println!` calls I make. I then reduced the number of calls and made the thing hopefully more rational. I hope it will improve the situation.

**Comment by ticki** [comment]
Nice!

**Pull request merged**
